# Site settings
title: samyakchoudhary.com
email: samyakchoudhary@gmail.com
description: Computer Science, IIT Roorkee, graduate. Aspiring Entrepreneur. ENTP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "samyakchoudhary.com" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-user']
  LinkedIn : ['LinkedIn','https://www.linkedin.com/in/samyakchoudhary/', 'fa-anchor']
  Facebook : ['Facebook','http://facebook.com/samyak.choudhary.355', '/img/facebook.png']
  Instagram : ['Instagram','http://instagram.com/samyak.choudhary/', 'fa-anchor']
  Quora : ['Quora','https://www.quora.com/profile/Samyak-Choudhary', 'fa-anchor']
  Email : ['Email','mailto:samyakchoudhary@gmail.com', 'fa-anchor']


single_footer: '<a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Home : ['Home', '/']

# Build settings
markdown: kramdown
